you need to edit each file with the update and fixes directly:
ReferenceError: useMemo is not defined
    at useKucoinAllTickersSocket (https://6000-firebase-studio-1747864089303.cluster-3ch54x2epbcnetrm6ivbqqebjk.cloudworkstations.dev/_next/static/chunks/src_0264d38d._.js:3787:30)
    at AllTickersScreener (https://6000-firebase-studio-1747864089303.cluster-3ch54x2epbcnetrm6ivbqqebjk.cloudworkstations.dev/_next/static/chunks/src_0264d38d._.js:3845:225)
    at MainViews (https://6000-firebase-studio-1747864089303.cluster-3ch54x2epbcnetrm6ivbqqebjk.cloudworkstations.dev/_next/static/chunks/src_0264d38d._.js:5550:229)
    at HomePage (https://6000-firebase-studio-1747864089303.cluster-3ch54x2epbcnetrm6ivbqqebjk.cloudworkstations.dev/_next/static/chunks/src_0264d38d._.js:9543:235)
    at ClientPageRoot (https://6000-firebase-studio-1747864089303.cluster-3ch54x2epbcnetrm6ivbqqebjk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)